services:
  - type: web
    name: crop-advisor-api
    env: node
    buildCommand: cd server && pnpm install && pnpm build
    startCommand: cd server && pnpm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGODB_URI
        sync: false
      - key: PORT
        value: 3001 